apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name | default "letsencrypt-issuer" }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretName | default "letsencrypt-account-key" }}
    solvers:
      - dns01:
          route53:
            region: {{ .Values.clusterIssuer.region | default "us-east-1" }}
            hostedZoneID: {{ .Values.clusterIssuer.hostedZoneID }}