alertmanager:
  # Mount the Secret into Alertmanager pods
  alertmanagerSpec:
    secrets:
      - alertmanager-slack

  # Replace the default routing tree to send alerts to Slack
  config:
    global:
      resolve_timeout: 5m

    # Keep Watchdog muted (default behavior), send everything else to Slack
    route:
      group_by: ["namespace","alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: slack-default
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: null
        - matchers:
            - severity = "critical"
          receiver: slack-critical

    receivers:
      - name: slack-default
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/alertmanager-slack/slack_webhook
            send_resolved: true
            # You can omit "channel" to use the channel attached to the webhook,
            # or override it here:
            channel: "#oncall-devops"
            title: >-
              [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} ({{ .CommonLabels.severity | default "n/a" }})
            text: >-
              {{- range .Alerts -}}
              • *{{ .Labels.namespace }}*: {{ .Annotations.summary | default .Annotations.message | default .CommonLabels.alertname }}
                {{- if .Annotations.description }} — {{ .Annotations.description }}{{- end }}
              {{- end }}

      - name: slack-critical
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/alertmanager-slack/slack_webhook
            send_resolved: true
            channel: "#oncall-devops"

      - name: null

    templates:
      - "/etc/alertmanager/config/*.tmpl"