name: Build Application

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Create ECR repository if not exists
        run: |
          aws ecr describe-repositories --repository-names hello-world-js --region us-east-1 || \
          aws ecr create-repository --repository-name hello-world-js --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Build Docker image
        run: docker build -t ${{ vars.Account_ID }}.dkr.ecr.us-east-1.amazonaws.com/hello-world-js:${{ github.run_number }} ./app

      - name: Push Docker image to ECR
        run: docker push ${{ vars.Account_ID }}.dkr.ecr.us-east-1.amazonaws.com/hello-world-js:${{ github.run_number }}